### ISSUE TITLE
LT2_6X Windows compile broken due to unable to include "endian.h" in pbkdf2_sha256.c

### ISSUE THREAD

**Issue by cgalik** [longturn/freeciv#11]
endian.h isn't available or needed for Windows build and is presently included in pbkdf2_sha256.c.

**Comment by lmoureaux** [comment]
`pbkdf2_sha256.c` is a LT specific file used for password hashing. I bet was never tested on Windows.

**Comment by lmoureaux** [comment]
Fixed in #12
